In [1]:
#导入numpy
import numpy as np

In [2]:
a = [1,2,3,4,5,6,7,8,9]
print(a)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [3]:
a * 2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
print(type(a))

<class 'list'>


In [5]:
#把普通Python中的list转换成ndarray
A = np.array(a)
print(A)
A

[1 2 3 4 5 6 7 8 9]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
print(type(A))

<class 'numpy.ndarray'>


In [7]:
A * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
#直接创建一维数组
b = np.array([1,2,3,4,5])
print(b)
print(type(b))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [9]:
b * 6

array([ 6, 12, 18, 24, 30])

In [10]:
#创建多维数组
c = np.array([[1,2,3],[4,5,6]])
print(c)
print(type(c))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [11]:
c * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [12]:
cc = [[1,2,3],[4,5,6]]
cc * 2

[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]

In [13]:
#创建多维数组
c = np.array([[1,2,3],[4,5,6]])
print(c)
print(type(c))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [14]:
c * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [15]:
cc = [[1,2,3],[4,5,6]]
cc * 2

[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]

In [16]:
print(c.ndim)

2


In [17]:
print(c.shape)

(2, 3)


In [18]:
print(c.size)

6


In [19]:
print(c.dtype)

int32


In [20]:
print(type(c))

<class 'numpy.ndarray'>


In [21]:
d = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(d)
print(d.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


In [22]:
print(d.shape)

(1, 3, 3)


In [24]:
print(d.size)

9


In [25]:
dd = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print(dd)
print(dd.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


In [26]:
print(dd.shape)

(2, 3, 3)


In [27]:
print(dd.size)

18


In [29]:
#指定维度来创建多维数组
e = np.array([1,2,3,4,5,6],ndmin=3)
print(e)

[[[1 2 3 4 5 6]]]


In [30]:
e.dtype

dtype('int32')

In [31]:
type(e)

numpy.ndarray

In [32]:
print(e.shape)

(1, 1, 6)


In [33]:
print(e.itemsize)

4


In [34]:
#指定维度和数值类型来创建多维数组
f = np.array([1,2,3,4,5,6],ndmin=3,dtype=np.complex)
print(f)

[[[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j]]]


In [35]:
print(f.itemsize)

16


In [36]:
f.data

In [37]:
f.flat

In [39]:
#声明一个dtype类型对象
dt = np.dtype(np.int32)
print(dt)

int32


In [40]:
#声明一个dtype类型对象2
dt = np.dtype(int)
print(dt)

int32


In [41]:
#如何使用上面创建的dt对象
a = np.array([1,2,3,4,5,6],dtype=dt)
print(a)

[1 2 3 4 5 6]


In [42]:
#声明一个float类型的dtype
dt_f = np.dtype(np.float32)
b = np.array([1,2,3,4,5,6],dtype=dt_f)
print(b)

[1. 2. 3. 4. 5. 6.]


In [43]:
#声明一个复数类型的dtype
dt_c = np.dtype(np.complex)
c = np.array([1,2,3,4,5,6],dtype=dt_c)
print(c)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j]


In [44]:
#numpy.empty以随机的方式来创建数组
a = np.empty([3,2],dtype=np.int32)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [45]:
#numpy.zeros返回指定大小的数组，并且以0作为填充
b = np.zeros([5,6],dtype=np.float32)
print(b)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [46]:
#np.zeros_like()
c = np.array([[1,2,3],[4,5,6]],dtype=np.float32)
print(c)

[[1. 2. 3.]
 [4. 5. 6.]]


In [47]:
d = np.zeros_like(c)
print(d)

[[0. 0. 0.]
 [0. 0. 0.]]


In [48]:
#numpy.ones返回指定数组大小的数组，并且以1来填充
a = np.ones([3,4],dtype=np.float32)
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [49]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]],dtype=np.float32)
print(b)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


In [50]:
#numpy.ones_like()
c = np.ones_like(b)
print(c)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [51]:
#numpy.eye函数返回对角线为1，其余为0的数组
d = np.eye(5)
print(d)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [52]:
d = np.eye(5,dtype=np.int32)
print(d)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [53]:
#数组创建
#numpy.asarray()主要是把python中的list和元组转换成numpy中的ndarray
x = [1,2,3,4,5,6]
a = np.asarray(x)
print(type(x))
print(type(a))
print(x)
print(a)

<class 'list'>
<class 'numpy.ndarray'>
[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]


In [54]:
y = (1,2,3,4,5,6)
b = np.asarray(y)
print(type(y))
print(type(b))
print(y)
print(b)

<class 'tuple'>
<class 'numpy.ndarray'>
(1, 2, 3, 4, 5, 6)
[1 2 3 4 5 6]


In [55]:
x = np.arange(10)
print(type(x))
print(x)

<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]


In [56]:
x = np.arange(10,dtype=np.float32)
print(x)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [57]:
x = np.arange(10,20,2,dtype=np.int32)
print(x)

[10 12 14 16 18]


In [58]:
x = np.linspace(10,20,5)
print(x)

[10.  12.5 15.  17.5 20. ]


In [59]:
#retstep = True 返回步长值
np.linspace(10,20,5,retstep=True)

(array([10. , 12.5, 15. , 17.5, 20. ]), 2.5)

In [60]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [61]:
np.linspace(0,1,10,endpoint=False)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [62]:
np.linspace(0.1,1.1,10,endpoint=False)

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [63]:
np.logspace(0,2,20)

array([  1.        ,   1.27427499,   1.62377674,   2.06913808,
         2.6366509 ,   3.35981829,   4.2813324 ,   5.45559478,
         6.95192796,   8.8586679 ,  11.28837892,  14.38449888,
        18.32980711,  23.35721469,  29.76351442,  37.92690191,
        48.32930239,  61.58482111,  78.47599704, 100.        ])

In [64]:
np.linspace(0,2,20)

array([0.        , 0.10526316, 0.21052632, 0.31578947, 0.42105263,
       0.52631579, 0.63157895, 0.73684211, 0.84210526, 0.94736842,
       1.05263158, 1.15789474, 1.26315789, 1.36842105, 1.47368421,
       1.57894737, 1.68421053, 1.78947368, 1.89473684, 2.        ])